### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by toton6868** [pudo/pgcsv#2]
```
Traceback (most recent call last):
  File "/usr/local/bin/pgcsv", line 6, in <module>
    from pgcsv.cli import main
  File "/usr/local/lib/python2.7/site-packages/pgcsv/cli.py", line 4, in <module>
    from pgcsv.csv import open_csv
  File "/usr/local/lib/python2.7/site-packages/pgcsv/csv.py", line 3, in <module>
    from normality import guess_encoding
  File "/usr/local/lib/python2.7/site-packages/normality/__init__.py", line 7, in <module>
    from normality.paths import safe_filename  # noqa
  File "/usr/local/lib/python2.7/site-packages/normality/paths.py", line 2, in <module>
    from banal import decode_path
  File "/usr/local/lib/python2.7/site-packages/banal/__init__.py", line 1, in <module>
    from banal.lists import is_sequence, is_listish
  File "/usr/local/lib/python2.7/site-packages/banal/lists.py", line 5
    def is_sequence(obj: Any) -> bool:
                       ^
SyntaxError: invalid syntax
```

**Comment by pudo** [comment]
`banal` (which pgcsv depends on) has dropped Python 2 support. You can pin it to versions below 1.0.0 if you want to continue the old versions.
